# -*- coding: utf-8 -*-
"""221 Lab Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbAAT8DSX5X9p4CsrN2RPWce-PgqjdZW
"""

file1 = open('input.txt','r')
file2 = open('output.txt','w')

from queue import PriorityQueue
import math
path = []
def Dijkstra(source,dest):

    pq = PriorityQueue()

    visited = [0] * (N+1)
    dist = [math.inf] * (N+1)
    dist[source] = 0
  
    prev = {}
    pq.put((dist[source],source))

    while pq.empty() != True:
        u = pq.get()[source] 
        if u not in visited:
            visited[u] = 1
            edg = graph[u]
            if edg != None:
                for i in edg:
                    v = i[0]
                    alt = dist[u]+i[1]
                    if alt < dist[v]:
                        dist[v] = alt
                        prev[v] = u
                        pq.put((dist[v],v))
    # print(prev)  
    temp = dest
    while temp != source:
        path.append(temp)
        temp = prev[temp]
    path.append(temp)
    # print(path)
    path.reverse()
    
    return dist[dest]
            
    
graph = {}

N, M = map(int, file1.readline().split())

adj = [[] for x in range(N+1)]
for j in range(M):
    u, v, w = map(int, file1.readline().split())
    adj[u].append((v, w))
for i in range(N):
    graph[i] = adj[i]
graph[N] = None
# print(graph)


minDist = (Dijkstra(1,9))


file2.write('The minimum distance is: '+str(minDist)+'\n')
file2.write('The shortest path is: ')
for i in path:
    file2.write(str(i)+ ' ')

file1.close()
file2.close()

