# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#------------List--------------

file1 = open("graphIn2.txt", mode = "r")
file2 = open('adjList.txt','w')
node = int(file1.readline())

adlist = {}

for i in range(node):
    value = list(map(int, file1.readline().split()))
    adlist.update({value[0]:value[1:len(value)]})

file2.write(str(adlist))
file2.close()

#----------Matrix-------------

file3 =open('graphIn.txt',mode="r")
lines=file3.readlines()

temp1 = []

for i in lines:
  l1=i.strip()
  temp1.append(l1)

nodes = int(temp1[0])
adjMat = []

for i in range(nodes):
    temp = []
    for j in range(nodes):
        temp.append(0)
    adjMat.append(temp)

row = temp1[0]
col = temp1[1]
edges = []

for i in temp1[2::]:
  edges.append(i)
for i in edges:
    temp2=i.split(' ')
    row=int(temp2[0])
    col=int(temp2[1])
    adjMat[row-1][col-1] += 1
# print(adjMat)
file4=open('adjMat.txt',mode="w")
for i in adjMat:
  file4.writelines(str(i)+',')
file4.close()
file3.close()