# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#------------Task-4-----------
#This code doesn't work

file1 = open("Task4In.txt",mode = "r")
t = int(file1.readline()) 

graph1 = {}
nodes1 = list(map(int, file1.readline().split()))

for i in range(nodes1[1]):
    value = list(map(str, file1.readline().split()))
    graph1.update({value[0]:(value[1])})


graph2 = {}
nodes2 = list(map(int, file1.readline().split()))

for i in range(nodes2[1]):
    value1 = list(map(str, file1.readline().split()))
    graph2.update({value1[0]:value1[1:len(value)]})


file2 = open("Out4.txt", "w")

visited = []
q = []
path = []

def bfs(visited, graph, node, endPoint):
    visited.append(node)
    queue.append(node)
    
    while q:
        m = q.pop(0)
        path.append(m)


        if m == endPoint:
            break

        for neigbor in graph[m]:
            if neigbor not in visited:
                visited.append(neigbor)
                q.append(neigbor)

    file2.write(str(len(path)-1)+"\n")



bfs(visited, graph1, '1', str(nodes1[0]))
bfs(visited, graph2, '1', str(nodes2[0]))


file2.close()
