# -*- coding: utf-8 -*-
"""task2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

file1 = open("graphIn2.txt", "r")
nodes = int(file1.readline())

visited = []
queue = []

file2 = open('bfsOut.txt','w')

def BFS(visited, graph, node, endPoint):

    visited.append(node)
    queue.append(node)
    
    while queue:
        m = queue.pop(0)
        #print(m, end=" ")
        file2.write(str(m)+' ')

        if m == endPoint:
            break

        for neighbour in graph[m]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)

graph = {}
for i in range(nodes):
    value = list(map(str, file1.readline().split()))
    graph.update({value[0]:value[1:len(value)]})

BFS(visited, graph, '1', '12')

file1.close()
file2.close()

