# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

file1 = open("graphIn2.txt", "r")
nodes = int(file1.readline())

visited = []
path = []
file2 = open("dfsOut.txt", "w")

def dfs_visit(graph, node):
    if node not in path:
        path.append(node)
        
        for each_node in graph[node]:
            if each_node not in visited:
                dfs_visit(graph, each_node)

def dfs(graph, endPoint):

    for each_node in graph:
        if each_node not in visited:
            dfs_visit(graph, each_node)
    
    for i in path:
        file2.write(i+' ')
        if i == endPoint:
            break

graph = {}
for i in range(nodes):
    value = list(map(str, file1.readline().split()))
    graph.update({value[0]:value[1:len(value)]})

dfs(graph, '12')

file2.close()

