# -*- coding: utf-8 -*-
"""task-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-3---------#

file1 = open('task3_input.txt','r')
file2 = open('Task3_output.txt','w')

str1 = file1.readline()
str2 = file1.readline()
str3 = file1.readline()

def LCS(X, Y, Z):
    m = len(X) - 1
    n = len(Y) - 1
    o = len(Z) - 1
    lst = [[[None] * (o + 1) for i in range(n + 1)] for y in range(m + 1)]

    for i in range(m + 1):
        for j in range(n + 1):
            for k in range(o + 1):
                if(i == 0 or j == 0 or k == 0):
                    lst[i][j][k] = 0
                elif(X[i - 1] == Y[j - 1] == Z[k - 1]):
                    lst[i][j][k] = (lst[i - 1][j - 1][k - 1] + 1)
                else:
                    lst[i][j][k] = max(lst[i-1][j][k], lst[i][j - 1][k], lst[i][j][k - 1])

    return lst[m][n][o]


length = LCS(str1, str2, str3)
file2.write(str(length))

file1.close()
file2.close()

