# -*- coding: utf-8 -*-
"""task-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-1---------#

file1 = open('Task1_input.txt','r')
file2 = open('Task1_output.txt','w')

def zero(n):

    arr = [1000]*(n+1)
    arr[0] = 0
    for i in range(1,n+1):
        for dig in str(i):
            arr[i] = min(arr[i],arr[i-int(dig)] + 1)
    return arr[n]

n = int(file1.readline())
file2.write(str(zero(n)))

