# -*- coding: utf-8 -*-
"""task-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#--------------TASK-2----------------#
from queue import PriorityQueue
import math

file1 = open('Task1In.txt',mode = 'r')
file2 = open("Task2Out.txt", mode = "w")

graph = {}
path = []

def Dijkstra(source, dest):
    
    dist = [math.inf] * (dest+1)
    dist[source] = 0
    visited = [0] * (dest+1)
    prev = {}
    pq = PriorityQueue()
    pq.put((dist[source],source))

    while pq.empty() != True:
        u = pq.get()[source] 
        if u not in visited:
            visited[u] = 1
            eg = graph[u]
            if eg != None:
                for i in eg:
                    v = i[0]
                    alt = dist[u]+i[1]
                    if alt < dist[v]:
                        dist[v] = alt
                        prev[v] = u
                        pq.put((dist[v],v))
        
    tmp = dest
    
    while tmp != source:
        path.append(tmp)
        tmp = prev[tmp]
    path.append(tmp)

    path.reverse()
    
    return (dist[dest])




for i in range(int(file1.readline())):
    N, M = map(int, file1.readline().split())
    adj = [[] for x in range(N+1)]
    for j in range(M):
        u, v, w = map(int, file1.readline().split())
        adj[u].append((v, w))
    for i in range(N):
        graph[i] = adj[i]
    graph[N] = None
    #print(graph)
    minDistance = Dijkstra(1, N)
    file2.write(str(path)+'\n')
    graph.clear()
    path.clear()



file1.close()
file2.close()

