# -*- coding: utf-8 -*-
"""task-5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#--------------TASK-5----------------#
from queue import PriorityQueue
import math

file1 = open('Task5In.txt',mode = 'r')
file2 = open("Task5Out.txt",'w')


def Network(adj, source):
    pq = PriorityQueue()
    dist = [-math.inf] * len(adj)
    dist[source] = math.inf
    visited = [False] * len(adj)
    pq.put((-1 * dist[source], source))

    while pq.empty() != True:
        u = pq.get()[1]
        if visited[u]:
            continue
        visited[u] = True

        for v in adj[u]:
            alt = min(dist[u], v[1])
            if(alt > dist[v[0]]):
                dist[v[0]] = alt
                pq.put((-1 * dist[v[0]], v[0]))

    for i in range(len(dist)):
        if(dist[i] == math.inf):
            dist[i] = 0
        if(dist[i] == -math.inf):
            dist[i] = -1

    return (str(dist[1:]) + "\n")


for i in range(int(file1.readline())):
    N, M = map(int, file1.readline().split())
    graph = [[] for x in range(N + 1)]
    for j in range(M):
        u, v, w = map(int, file1.readline().split())
        graph[u].append((v, w))
    source = int(file1.readline())

    file2.write(Network(graph, source))
    
file1.close()
file2.close()

