# -*- coding: utf-8 -*-
"""task-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-2---------#

file1 = open("task2_input2.txt", "r")
file2 = open('task2_Out.txt','w')
N,M = list(map(int, file1.readline().split()))

intervals = []
for i in range(N):
    intervals.append(list(map(int, file1.readline().split())))


#sorting
intervals = sorted(intervals,key = lambda x:x[1])

'''for i in range(N):
    for j in range(0, N-1):
        if intervals[j][1] > intervals[j+1][1]:
            intervals[j],intervals[j+1] = intervals[j+1],intervals[j]'''


def schedule_intervals(intervals):

    count = 1
    for i in range(len(intervals)-1):
        if intervals[i][1] > intervals[i+1][0]:
            count += 1
            
    file2.write(str(count))
schedule_intervals(intervals)