# -*- coding: utf-8 -*-
"""task-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-1---------#
file1 = open("task1_input.txt", "r")
file2 = open('task1_out.txt','w')
N = int(file1.readline())

arr = []
for i in range(N):
    arr.append(list(map(int, file1.readline().split())))

#sorting by finish time
'''for i in range(N):
    for j in range(N-1):
        if arr[j][1] > arr[j+1][1]:
            arr[j],arr[j+1] = arr[j+1],arr[j]'''
arr = sorted(arr,key = lambda x:x[1])
            

def assignemnt_selection(arr):
    count = 0
    selected = []
    selected.append(arr[0])
    count += 1
    fintime = arr[0][1] 

    for i in arr:
        if i[0] >= fintime:
            fintime = i[1]
            selected.append(i)
            count += 1

    # print(count)
    file2.write(str(count)+'\n')

    for i in selected:
        file2.write(str(i[0]) + " " + str(i[1])+'\n')
        # print(str(i[0])+' '+str(i[1]))
assignemnt_selection(arr)