# -*- coding: utf-8 -*-
"""task-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-3---------#
from collections import deque
 
stack = deque()

file1 = open('task3_input.txt','r')
file2 = open('task3_out.txt','w')
 
n = int(file1.readline())
taskTime = file1.readline().split()
taskTime = sorted(taskTime)
call = file1.readline().split()[0]
hrSeq = ''
hourJack = 0
jackwork = []
hourjill = 0

i = 0

for c in call:
        
        if c == 'J':
            stack.append((taskTime[i]))
            hourJack += int(taskTime[i])
            hrSeq += (taskTime[i])
            i+=1

        elif c == 'j':
            pop = stack.pop()
            hrSeq += pop
            hourjill += int(pop)


file2.write(hrSeq+'\nJack will work for '+str(hourJack)+' hours\nJill will work for '+str(hourjill)+' hours')