# -*- coding: utf-8 -*-
"""task-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otnQg8J0BGgX6bC1SpzdJrFF2xyWjyUr
"""

#---------Task-4---------#
import math

file1 = open('task4_input.txt','r')
file2 = open('task4_out.txt','w')
for i in file1.readlines():
    a,b = i.split()
    a,b = int(a),int(b)

    def findSqr(a,b):
        count = 0
        for i in range(a,b+1):
            if a == 0 and b == 0:
                break
            if math.sqrt(i).is_integer():
                count += 1
        return count
        
    file2.write(str(findSqr(a,b))+'\n')