# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Hl-yPdpPWgF3_TeFy_rhYRQKybIQpYN
"""

#-----------------TASK-2-----------------


def selectionSort(arr):

    file1 = open('selSort.txt',mode = 'r')
    line1 = file1.readline()
    N,M = line1.split()
    M = int(M)

    arr1 = []
    arr1 = file1.readline().split()
    arr = []
    for i in arr1:
        arr.append(int(i))
    
    file2 = open('selSortOut.txt',mode = 'w')

    for i in range (0,len(arr)-1,):
        minp=i
        for j in range(i,len(arr)):
            if arr[j]<arr[minp]:
                minp=j
        temp=arr[i]
        arr[i]=arr[minp]
        arr[minp]=temp
    
    for i in (arr[:M]):
        file2.write(str(i)+' ')
    
    #file2.write(s1)
    file2.close()
    file1.close()

selectionSort(arr)