# -*- coding: utf-8 -*-
"""Task-5(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Hl-yPdpPWgF3_TeFy_rhYRQKybIQpYN
"""

#-----------------TASK-5(b)-------------------
file1 = open('5(b)In.txt',mode = 'r')

n = file1.readline()
arr1 = []
arr1 = file1.readline().split()
arr = []

for i in arr1:
    arr.append(int(i))

def findK(arr,low,high,k):
    file2 = open('5(b)Out.txt','w')

    if low > high:
        return

    mid = (low + high) // 2

    if k == arr[mid]:
        mid1 = str(mid)
        file2.write('It is at index '+ mid1)
        

    if k < arr[mid]:
        return findK(arr,low,mid - 1,k)

    return findK(arr,mid + 1,high,k)

    file2.close()
findK(arr,0,len(arr)-1,4)

