# -*- coding: utf-8 -*-
"""Task-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Hl-yPdpPWgF3_TeFy_rhYRQKybIQpYN
"""

#-----------------TASK-3-------------------

file1 = open('insertSort.txt',mode = 'r')
x = file1.readline()
id = []
id = file1.readline().split()
mark = []
mark = file1.readline().split()
ids = []
marks = []
for i in mark:
    marks.append(int(i))
for i in id:
    ids.append(int(i))

def insertSort(marks):
    file2 = open('InsertOut.txt',mode = 'w')

    for i in range(len(marks)):
        minpos = marks[i] 
        idmin = ids[i]
        j = i-1      
       
        while j >= 0 and minpos > marks[j] :
                marks[j+1] = marks[j]
                ids[j+1] = ids[j]
                j -= 1
        marks[j+1] = minpos
        ids[j+1] = idmin

    #print(ids)
    for i in ids:
        file2.write(str(i)+' ')

insertSort(marks)