# -*- coding: utf-8 -*-
"""Task-5(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Hl-yPdpPWgF3_TeFy_rhYRQKybIQpYN
"""

#-----------------TASK-5(a)-------------------
import time

file1 = open('quick.txt',mode = 'r')

n = file1.readline()
arr1 = []
arr1 = file1.readline().split()
arr = []

for i in arr1:
    arr.append(int(i))
print('Unsorted array: ',arr)
start_time = time.time()

def partition(low,high):

    i = low
    j = high
    pivot = arr[low]
    while i < j:
        if arr[i] < pivot:
            i += 1
        if arr[j] > pivot:
            j -= 1
        if i < j:
            arr[i],arr[j] = arr[j],arr[i]
    arr[i],arr[j] = arr[j],arr[i]
    return j

def quick_sort(low, high):
    if low < high:
        j = partition(low,high)
        quick_sort(low,j)
        quick_sort(j+1,high)

        return f'Sorted Array: {arr}'
        
        
print(quick_sort(0,len(arr)-1))
print("Sort runtime %s seconds" % (time. time() - start_time))