# -*- coding: utf-8 -*-
"""Task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Hl-yPdpPWgF3_TeFy_rhYRQKybIQpYN
"""

#-----------------TASK-4-------------------

file1 = open('merge.txt',mode = 'r')
n = file1.readline()
arr1 = []
arr1 = file1.readline().split()
arr = []
for i in arr1:
    arr.append(int(i))


def merge_sort(arr,p,q,r):
    file2 = open('mergeOut.txt',mode = 'w')
    if len(arr) > 1:
        mid = len(arr)//2
        left = arr[:mid]
        right = arr[mid:]
        #print(left,right)
            #recursion
        merge_sort(left,p,mid+1,r)
        merge_sort(right,mid+1,q+1,r)
            
        #merge
        i = 0 #left ind
        j = 0 #rt ind
        k = 0 #merged
            
        while i < len(left) and j < len(right):
            if left[i]<right[j]:
                arr[k] = left[i]
                i += 1
                k+= 1
            else:
                arr[k] = right[j]
                j += 1
                k += 1

        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1

        for i in arr:
            file2.write(str(i)+' ')
        file2.close()

merge_sort(arr,p = 0,q = len(arr)-1,r = 0)